- kernel-crawler/rhel-login/Dockerfile
On newer UBI images susbscription-manager is installed by default, so we should be safe to skip it if installation breaks.
> Skip subscription-manager install if broken

- kernel-crawler/kernel-crawler.py
Seems the release of Docker Desktop for Linux has prompted a restructuring of the release notes page, this in turn broke our crawler. Replacing the URLs with their new counter parts should fix the issue.
> Fix crawling URLs for Docker Desktop

- .openshift-ci/google-cloud-sdk/init.sh
- .openshift-ci/google-cloud-sdk/install.sh
There seems to be no standartized way of installing google-cloud-sdk,
simulare gcloud-orb explicitely via scripts.
> Prepare scripts for google-cloud-sdk

- kernel-package-lists/reformat.yml
Minikube repackaging is broken for v1.26.0, this PR disables it temporarily while we look to fix it.
Tracking issue: [ROX-11521](https://issues.redhat.com/browse/ROX-11521)
> Disable minikube repackage

- .openshift-ci/crawler/setup-staging.sh
For testing purposes and avoiding timeout limits, point crawler to a pre-populated part of the buckets.
> Point to a copy path for staging bucket

- .openshift-ci/gcp/command.sh
- .openshift-ci/gcp/create-vm.sh
- scripts/robo-crawl-commit
To reuse the keys and avoid polluting project metadata.
> Specify ssh keys for command script

- .openshift-ci/crawler/collector.sh
Use collector commit target, the robo-crawl-commit already runs in the `/.openshift-ci/crawler/sync.sh`
> Fix collector commit

- kernel-crawler/garden-crawler.py
This is a quick and dirty fix to the garden linux crawler.
Some new entries that match the metadata label we look for have been added into their `component-descriptor` file that don't container the `debianPackages` entry, this PR make said entry optional.
> Make 'debianPackages' optional in garden linux crawler

- .openshift-ci/slack/notify.sh
The notification is important only for the periodical jobs
> Do not notify on PRs

- kernel-crawler/Dockerfile
- kernel-crawler/Makefile
- kernel-crawler/kernel-crawler.py
- kernel-crawler/minikube-crawler.py
- kernel-crawler/requirements.txt
- kernel-package-lists/reformat.yml
- packers/entrypoint
- tools/command/command.go
- tools/generate-manifest/reformatters/reformatters.go
This PR refactors minikube kernel crawling and repackaging.
The new way of crawling is to use the minikube repository, going through its tags and taking note of both the path to the kernel config file and version being used to build their ISO. Then the crawler outputs a GitHub raw URL for the config file and a cdn.kernel.org URL to the vanilla header files.
Repackaging is mostly the same as the existing `linuxkit` repackager, but using the config file downloaded from github with the vanilla kernel headers.
> New minikube crawling

- kernel-crawler/Makefile
- kernel-crawler/kernel-crawler.py
The URLs were still being crawled, but new Garden Linux kernels are actually retrieved from GitHub's release artifacts. So these should be safe to remove.
> Remove unreachable and unused Garden Linux URLs

- .openshift-ci/crawler/env.sh
Add the newly created SUSE secret crawling credentials to the list of secrets being used.
> Allow access to SUSE credentials

- kernel-crawler/Dockerfile
This change makes it so the p7zip tarball for compilation is downloaded directly from the official repository. Looks like this repo was moved to the official `p7zip-project`organization and re-forked, which in turn removed the releases we were relaying on,
> Use official version of p7zip

- .github/workflows/crawl.yml
This moves all the secrets to the top-level environment for the crawl job to avoid the possibility of missing a secret in each individual step.
> Fix missing secrets in crawl workflow

- .github/actions/env/action.yml
- .github/workflows/crawl.yml
- .github/workflows/repackage.yml
Once https://github.com/openshift/release/pull/35678 has merged, we will rely on GHA for kernel-packer. This PR ensures the correct buckets are used and enables the committing features.
> Enable production buckets and committing to the GHA workflows

- scripts/robo-crawl-commit
This is primarily to get some better visibility on the current failures on master
> Removes output suppression of robo-crawl-commit git push command

- .github/workflows/repackage.yml
I have a suspicion that the manifest file is incorrectly downloaded to the repo root directory and that prevents the repackaging step from picking up new crawled kernels.
> Fix manifest file download directory

- kernel-package-lists/gardenlinux-uncrawled.txt
This PR adds the missing packages for version 934.2 of Garden Linux. I will be following this PR with a bump to the VM being used for testing in stackrox/collector.
> Add uncrawled Garden Linux packages

- .github/workflows/repackage.yml
In the repackaging step, the manifest is downloaded to the root of the directory instead of the kernel-package-lists directory, which results in some mistakes in repackaging. This fixes that by defining the download path.
> Fixes manifest download in repackaging step

- kernel-package-lists/gardenlinux-uncrawled.txt
This PR adds the packages needed for the latest Garden Linux version.
> Add kernels for 934.3 Garden Linux version

- scripts/sync
Suppresses broken pipe errors when echoing into `grep -q`, which may exit early and break the stdout of echo
> Improves logging clarity

- .github/workflows/crawl.yml
- .github/workflows/repackage.yml
Following the slack migration, this should restore notifications in the oncall dedicated collector channel.
> Update the slack channel name for oncall notifications

- kernel-crawler/garden-crawler.py
After the component-descriptor was re-added to the Garden Linux releases, a few tweaks are needed in our crawler for it to work again.
> Minor fixes to the Garden Linux crawler

- .github/workflows/crawl.yml
When running in PRs that skip the crawling stage, the errors artifact isn't created and causes the error check stage fail. This can be solved by adding an empty file that forces the artifact to be created.
> Ensure PRs don't fail when not crawling

- .github/workflows/main.yml
The regex used for checking the crawler output for make error lines has been broken since its implementation. This commit fixes it by adding colons and spaces to the contents of the group between brackets.
> Fix the regex used for searching make errors

- tools/generate-manifest/reformatters/reformatters.go
Debian crawler discovered linux-kbuild-4.9.0-13 was removed from [[1]], leaving only linux-kbuild-4.9_4.9.228, but not for amd64 architecture. At the same time linux-headers-4.9.0-13 are still there (including amd64). Which is a problem for reformatter, as it tries to match every header and kbuild package. Since not much could be done about missing package, downgrade the error to a log message and continue with the rest.
[1]: http://debian.csail.mit.edu/debian/pool/main/l/linux/
> Downgrade missing kbuild error

- .github/workflows/main.yml
When making the trigger event types explicit, in order to add the label related ones,
the 'synchronized' one was forgotten.
> Trigger pipeline on PR push

- kernel-crawler/kernel-crawler.py
w.r.t the Ubuntu kernel only the all package is available for this kernel and it causes the crawler to fail, so we should block it.
The COS kernel has a known issue upstream in the v6.8.2 were some header includes are missing, so we'll block that one since we cannot compile it.
> Block Ubuntu kernel 6.8.0-20.20 and cos 18342

- .github/workflows/crawl.yml
- .github/workflows/repackage.yml
- scripts/robo-collector-commit
- scripts/robo-crawl-commit
`roxbot` is being retired in favor of `rhacs-bot`.
- committed to a test branch on collector with the same protection rule override as main: https://github.com/stackrox/collector/commits/gavin/test-kerel-packer-collector-commit/
> chore(CI): use rhacs-bot
